const generateImages = (url) => [
  url,
  url + "&1",
  url + "&2",
  url + "&3"
];
export const API_BASE_URL = "http://localhost:5000/api";
export const CATEGORIES = [
  'Electronics',
  'Home & Kitchen',
  'Fashion',
  'Books',
  'Sports & Outdoors',
  'Beauty & Personal Care',
  'Toys & Games',
  'Automotive'
];

export const MOCK_PRODUCTS = [
  // --- ELECTRONICS (20) ---
  {
    id: 'e1',
    name: 'Premium Wireless Headphones',
    description: 'High-quality noise-canceling headphones with 40-hour battery life.',
    price: 299.99,
    originalPrice: 349.99,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1240,
    stock: 15,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: ['Best Seller', 'On Sale'],
    brand: 'AudioPro',
    material: 'Aluminum & Leather',
  },
  {
    id: 'e2',
    name: 'Smart Fitness Tracker',
    description: 'Water-resistant tracker with heart rate and sleep monitoring.',
    price: 79.99,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.2,
    reviewCount: 560,
    stock: 25,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: ['Best Seller'],
    brand: 'FitTrack',
    material: 'Silicone',
  },
  {
    id: 'e3',
    name: 'Professional DSLR Camera',
    description: 'Capture stunning photos with this 24.2MP full-frame sensor camera.',
    price: 1299.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 320,
    stock: 8,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'OpticMaster',
  },
  {
    id: 'e4',
    name: 'Ultra-Slim Laptop 14"',
    description: 'Powerful performance in a portable design with 16GB RAM and 512GB SSD.',
    price: 949.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1496181133206-80ce9b88a853?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 890,
    stock: 12,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'SwiftBook',
  },
  {
    id: 'e5',
    name: 'Noise Cancelling Earbuds',
    description: 'True wireless earbuds with immersive sound and sweat resistance.',
    price: 159.99,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 2100,
    stock: 45,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'SonicWave',
  },
  {
    id: 'e6',
    name: '4K Ultra HD Smart TV',
    description: 'Experience cinematic visuals with HDR support and built-in streaming apps.',
    price: 549.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1500,
    stock: 10,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'VisionPlus',
  },
  {
    id: 'e7',
    name: 'Gaming Mechanical Keyboard',
    description: 'RGB backlit keys with tactile switches for ultimate gaming precision.',
    price: 129.50,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 740,
    stock: 30,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'GameForce',
  },
  {
    id: 'e8',
    name: 'Portable Bluetooth Speaker',
    description: 'Rugged, waterproof speaker with 360-degree sound and deep bass.',
    price: 89.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1608156639585-b3a032ef9689?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 1200,
    stock: 55,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'BoomBox',
  },
  {
    id: 'e9',
    name: 'Wireless Charging Pad',
    description: 'Fast charging for all Qi-enabled devices with a sleek fabric finish.',
    price: 34.99,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1615526675159-e248c3021d3f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.3,
    reviewCount: 450,
    discount: 20,
    stock: 100,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'PowerUp',
  },
  {
    id: 'e10',
    name: 'Action Camera 4K',
    description: 'Capture your adventures in stunning 4K with electronic image stabilization.',
    price: 199.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1526170315873-3a9161729b48?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 680,
    discount: 15,
    stock: 18,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'GoWild',
  },
  {
    id: 'e11',
    name: 'Smart Home Hub',
    description: 'Control your entire home with voice commands and automated routines.',
    price: 119.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 920,
    discount: 12,
    stock: 22,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'HomeSync',
  },
  {
    id: 'e12',
    name: 'External SSD 1TB',
    description: 'Lightning-fast data transfers in a compact, shock-resistant design.',
    price: 149.99,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1597740985671-2a8a3b80502e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 1100,
    stock: 40,
    discount: 0,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'DataDrive',
  },
  {
    id: 'e13',
    name: 'Curved Gaming Monitor',
    description: '32-inch QHD display with 144Hz refresh rate for fluid gameplay.',
    price: 399.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 530,
    stock: 15,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'PixelPerfect',
  },
  {
    id: 'e14',
    name: 'Smart Doorbell Camera',
    description: 'See and speak to visitors from anywhere with 1080p HD video.',
    price: 179.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 840,
    stock: 28,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'SecureEntry',
  },
  {
    id: 'e15',
    name: 'Graphic Tablet',
    description: 'Natural pen-on-paper feel for digital artists and designers.',
    price: 249.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1544244015-0df4b3ffc69d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 610,
    stock: 14,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'ArtPad',
  },
  {
    id: 'e16',
    name: 'Smart Light Bulb Set',
    description: 'Millions of colors and tunable white light, compatible with Alexa.',
    price: 49.99,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1550524514-9636edecdd04?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1300,
    stock: 75,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'Lumina',
  },
  {
    id: 'e17',
    name: 'Wireless Gaming Mouse',
    description: 'Ultra-lightweight with a high-precision sensor and long battery life.',
    price: 69.50,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 980,
    stock: 42,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'SwiftClick',
  },
  {
    id: 'e18',
    name: 'E-Reader Paperwhite',
    description: 'Glare-free display that reads like real paper, even in bright sunlight.',
    price: 139.99,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 2500,
    stock: 35,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'ReadWell',
  },
  {
    id: 'e19',
    name: 'Smart Thermostat',
    description: 'Save energy and stay comfortable with intelligent temperature control.',
    price: 229.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 470,
    stock: 16,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'EcoTemp',
  },
  {
    id: 'e20',
    name: 'VR Headset Elite',
    description: 'Immerse yourself in virtual worlds with high-resolution displays.',
    price: 499.00,
    category: 'Electronics',
    images: generateImages('https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 310,
    stock: 9,
    vendorId: 'v1',
    vendorName: 'TechHub Solutions',
    badges: [],
    brand: 'RealityX',
  },

  // --- HOME & KITCHEN (20) ---
  {
    id: 'h1',
    name: 'Ergonomic Office Chair',
    description: 'Breathable mesh back with adjustable lumbar support and armrests.',
    price: 189.50,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1505798577917-a65157d3320a?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 850,
    stock: 3,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: ['Low Stock', 'Top Rated'],
    brand: 'ErgoDesign',
    material: 'Mesh & Steel',
  },
  {
    id: 'h2',
    name: 'Chef\'s Knife Set',
    description: 'Professional grade stainless steel knives with ergonomic handles.',
    price: 129.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1593618998160-e34014e67546?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 620,
    stock: 20,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'CulinaryPro',
  },
  {
    id: 'h3',
    name: 'Air Fryer XL',
    description: 'Cook your favorite fried foods with up to 85% less fat.',
    price: 119.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1585515320310-259814833e62?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1800,
    stock: 15,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'CrispAir',
  },
  {
    id: 'h4',
    name: 'Memory Foam Pillow',
    description: 'Contoured support for a better night\'s sleep, cooling gel infused.',
    price: 49.50,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1520390138845-fd2d229dd553?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 2400,
    stock: 60,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'SleepTight',
  },
  {
    id: 'h5',
    name: 'Electric Kettle',
    description: 'Fast boiling with auto shut-off and boil-dry protection.',
    price: 39.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 1100,
    stock: 40,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'QuickBrew',
  },
  {
    id: 'h6',
    name: 'Robot Vacuum Cleaner',
    description: 'Smart navigation and powerful suction for effortless floor cleaning.',
    price: 299.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 780,
    stock: 12,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'CleanBot',
  },
  {
    id: 'h7',
    name: 'Non-Stick Cookware Set',
    description: '12-piece set with durable non-stick coating and glass lids.',
    price: 159.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1584990344619-39110fe720a5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 950,
    stock: 25,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'KitchenMaster',
  },
  {
    id: 'h8',
    name: 'Espresso Machine',
    description: 'Authentic espresso at home with a powerful 15-bar pump.',
    price: 199.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 540,
    stock: 8,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'BaristaPro',
  },
  {
    id: 'h9',
    name: 'Bamboo Cutting Board',
    description: 'Eco-friendly and durable, gentle on your knives.',
    price: 24.50,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1300,
    stock: 100,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'EcoKitchen',
  },
  {
    id: 'h10',
    name: 'Slow Cooker',
    description: 'Programmable slow cooker for easy, delicious family meals.',
    price: 69.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 890,
    stock: 30,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'SlowChef',
  },
  {
    id: 'h11',
    name: 'Cotton Bed Sheet Set',
    description: 'Soft and breathable 400 thread count Egyptian cotton.',
    price: 79.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1600,
    stock: 45,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'LuxeLinens',
  },
  {
    id: 'h12',
    name: 'Digital Kitchen Scale',
    description: 'Precise measurements for baking and portion control.',
    price: 19.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1591196702597-062a17206621?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 2200,
    stock: 150,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'WeightWise',
  },
  {
    id: 'h13',
    name: 'Glass Food Storage Containers',
    description: '10-piece set with airtight lids, microwave and oven safe.',
    price: 44.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1100,
    stock: 80,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'FreshLock',
  },
  {
    id: 'h14',
    name: 'Standing Desk Converter',
    description: 'Easily switch between sitting and standing at your desk.',
    price: 149.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1593642532842-98d0fd5ebc1a?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 430,
    stock: 10,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'ActiveWork',
  },
  {
    id: 'h15',
    name: 'Velvet Throw Blanket',
    description: 'Super soft and cozy, perfect for chilly evenings.',
    price: 34.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1580301762395-21ce84d00bc6?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1400,
    stock: 90,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'CozyHome',
  },
  {
    id: 'h16',
    name: 'Ceramic Dinnerware Set',
    description: 'Elegant 16-piece set for four, dishwasher safe.',
    price: 89.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1577202214328-c04b77cefb5d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 670,
    stock: 20,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'TableArt',
  },
  {
    id: 'h17',
    name: 'Handheld Milk Frother',
    description: 'Create creamy froth for lattes and cappuccinos in seconds.',
    price: 14.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1553909489-cd47e0907980?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 3500,
    stock: 200,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'FrothMaster',
  },
  {
    id: 'h18',
    name: 'Cast Iron Skillet',
    description: 'Pre-seasoned and ready to use, superior heat retention.',
    price: 29.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 4200,
    stock: 50,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'IronChef',
  },
  {
    id: 'h19',
    name: 'Aromatherapy Diffuser',
    description: 'Ultrasonic cool mist with 7 color-changing LED lights.',
    price: 39.00,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1602928321679-560bb453f190?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1100,
    stock: 65,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'ZenMist',
  },
  {
    id: 'h20',
    name: 'Spice Rack Organizer',
    description: 'Rotating rack with 16 pre-filled spice jars.',
    price: 49.99,
    category: 'Home & Kitchen',
    images: generateImages('https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 580,
    stock: 24,
    vendorId: 'v2',
    vendorName: 'Comfort Living',
    badges: [],
    brand: 'FlavorFlow',
  },

  // --- FASHION (20) ---
  {
    id: 'f1',
    name: 'Minimalist Leather Wallet',
    description: 'Genuine top-grain leather with RFID blocking technology.',
    price: 45.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1627123424574-724758594e93?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 2100,
    stock: 50,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: ['New Arrival'],
    brand: 'LeatherCo',
    material: 'Leather',
  },
  {
    id: 'f2',
    name: 'Organic Cotton T-Shirt',
    description: 'Soft, breathable 100% organic cotton tee in various colors.',
    price: 29.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 420,
    stock: 60,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: ['New Arrival'],
    brand: 'EcoWear',
    material: 'Organic Cotton',
    size: ['S', 'M', 'L', 'XL'],
  },
  {
    id: 'f3',
    name: 'Classic Denim Jacket',
    description: 'Timeless style with a comfortable fit and durable denim.',
    price: 89.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 850,
    stock: 30,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'DenimCo',
  },
  {
    id: 'f4',
    name: 'Polarized Sunglasses',
    description: 'UV400 protection with a stylish aviator frame.',
    price: 59.99,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1511499767390-903390e6fbc4?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1200,
    stock: 45,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'SunGuard',
  },
  {
    id: 'f5',
    name: 'Canvas Backpack',
    description: 'Spacious and durable, perfect for daily commute or travel.',
    price: 65.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 940,
    stock: 25,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'UrbanCarry',
  },
  {
    id: 'f6',
    name: 'Wool Blend Coat',
    description: 'Elegant and warm, a must-have for the winter season.',
    price: 199.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 320,
    stock: 10,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'WinterLuxe',
  },
  {
    id: 'f7',
    name: 'Casual Sneakers',
    description: 'Comfortable and versatile for everyday wear.',
    price: 75.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 1500,
    stock: 80,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'StepFree',
  },
  {
    id: 'f8',
    name: 'Silk Scarf',
    description: 'Luxurious 100% silk scarf with a vibrant floral print.',
    price: 49.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1584030373081-f37b7bb4fa8e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 210,
    stock: 15,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'SilkRoad',
  },
  {
    id: 'f9',
    name: 'Leather Belt',
    description: 'Classic design made from high-quality full-grain leather.',
    price: 35.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1554990772-0bea55d510d5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 560,
    stock: 100,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'BeltMaster',
  },
  {
    id: 'f10',
    name: 'Knit Beanie',
    description: 'Soft and warm acrylic knit, perfect for cold weather.',
    price: 19.99,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1100,
    stock: 150,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'WarmHead',
  },
  {
    id: 'f11',
    name: 'Linen Button-Down',
    description: 'Lightweight and breathable, ideal for summer days.',
    price: 55.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 430,
    stock: 40,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'SummerBreeze',
  },
  {
    id: 'f12',
    name: 'Ankle Boots',
    description: 'Stylish suede boots with a comfortable block heel.',
    price: 120.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 380,
    stock: 20,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'StepUp',
  },
  {
    id: 'f13',
    name: 'Crossbody Bag',
    description: 'Compact and practical for carrying your essentials.',
    price: 45.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 620,
    stock: 35,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'EasyCarry',
  },
  {
    id: 'f14',
    name: 'Cashmere Sweater',
    description: 'Incredibly soft and warm, a luxury staple for your wardrobe.',
    price: 150.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 150,
    stock: 12,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'SoftTouch',
  },
  {
    id: 'f15',
    name: 'Chino Pants',
    description: 'Classic slim-fit chinos made from comfortable stretch cotton.',
    price: 65.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1473966968600-fa801b869a1a?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 890,
    stock: 55,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'DailyFit',
  },
  {
    id: 'f16',
    name: 'Puffer Vest',
    description: 'Lightweight insulation for layering in transitional weather.',
    price: 79.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 310,
    stock: 25,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'LayerUp',
  },
  {
    id: 'f17',
    name: 'Aviator Watch',
    description: 'Rugged design with a large, easy-to-read dial and leather strap.',
    price: 185.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1524592094714-0f0654e20314?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 240,
    stock: 18,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'TimeMaster',
  },
  {
    id: 'f18',
    name: 'Cotton Scarf',
    description: 'Lightweight and soft, perfect for spring and autumn.',
    price: 25.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 520,
    stock: 70,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'SoftWrap',
  },
  {
    id: 'f19',
    name: 'Chelsea Boots',
    description: 'Classic design with elastic side panels for easy on and off.',
    price: 135.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1638247025967-b4e38f787b76?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 410,
    stock: 22,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'UrbanStep',
  },
  {
    id: 'f20',
    name: 'Denim Shorts',
    description: 'Casual and comfortable, a summer essential.',
    price: 39.00,
    category: 'Fashion',
    images: generateImages('https://images.unsplash.com/photo-1591195853828-11db59a44f6b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 680,
    stock: 45,
    vendorId: 'v3',
    vendorName: 'Heritage Crafts',
    badges: [],
    brand: 'SummerDenim',
  },

  // --- BOOKS (20) ---
  {
    id: 'b1',
    name: 'The Great Gatsby',
    description: 'A classic novel by F. Scott Fitzgerald about the American Dream.',
    price: 12.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 3500,
    stock: 100,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'ClassicPress',
  },
  {
    id: 'b2',
    name: 'Atomic Habits',
    description: 'An easy and proven way to build good habits and break bad ones.',
    price: 18.00,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 15000,
    stock: 200,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'SelfHelpHub',
  },
  {
    id: 'b3',
    name: 'The Alchemist',
    description: 'A magical story about following your dreams by Paulo Coelho.',
    price: 14.50,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 8200,
    stock: 150,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'InspireBooks',
  },
  {
    id: 'b4',
    name: '1984',
    description: 'George Orwell\'s dystopian masterpiece about surveillance and control.',
    price: 10.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1543004218-ee141104638e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 5600,
    stock: 80,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'ClassicPress',
  },
  {
    id: 'b5',
    name: 'Thinking, Fast and Slow',
    description: 'Daniel Kahneman explores the two systems that drive the way we think.',
    price: 22.00,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 4100,
    stock: 60,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'MindBooks',
  },
  {
    id: 'b6',
    name: 'The Hobbit',
    description: 'J.R.R. Tolkien\'s classic fantasy adventure.',
    price: 15.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1621351123083-b8825f55374b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 7300,
    stock: 90,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'FantasyWorld',
  },
  {
    id: 'b7',
    name: 'Sapiens',
    description: 'A brief history of humankind by Yuval Noah Harari.',
    price: 20.00,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 9400,
    stock: 110,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'HistoryHub',
  },
  {
    id: 'b8',
    name: 'Educated',
    description: 'A memoir by Tara Westover about the power of education.',
    price: 16.50,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1495446815901-a7297e633e8d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 3200,
    stock: 50,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'LifeStories',
  },
  {
    id: 'b9',
    name: 'The Silent Patient',
    description: 'A shocking psychological thriller by Alex Michaelides.',
    price: 14.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 6800,
    stock: 75,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'ThrillerPress',
  },
  {
    id: 'b10',
    name: 'Becoming',
    description: 'The deeply personal memoir of Michelle Obama.',
    price: 19.00,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 12000,
    stock: 130,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'LifeStories',
  },
  {
    id: 'b11',
    name: 'Where the Crawdads Sing',
    description: 'A beautiful and haunting novel by Delia Owens.',
    price: 13.50,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 18000,
    stock: 160,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'NatureFiction',
  },
  {
    id: 'b12',
    name: 'The Power of Habit',
    description: 'Why we do what we do in life and business by Charles Duhigg.',
    price: 17.00,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 5200,
    stock: 85,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'SelfHelpHub',
  },
  {
    id: 'b13',
    name: 'Man\'s Search for Meaning',
    description: 'Viktor Frankl\'s classic memoir about finding purpose in suffering.',
    price: 11.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1495446815901-a7297e633e8d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 4800,
    stock: 95,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'PhilosophyPress',
  },
  {
    id: 'b14',
    name: 'The 7 Habits of Highly Effective People',
    description: 'Stephen Covey\'s timeless guide to personal and professional success.',
    price: 15.00,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1512820790803-83ca734da794?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 9100,
    stock: 120,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'SelfHelpHub',
  },
  {
    id: 'b15',
    name: 'Dune',
    description: 'Frank Herbert\'s epic science fiction masterpiece.',
    price: 18.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1621351123083-b8825f55374b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 6400,
    stock: 70,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'SciFiWorld',
  },
  {
    id: 'b16',
    name: 'The Psychology of Money',
    description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel.',
    price: 16.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 8500,
    stock: 140,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'FinancePress',
  },
  {
    id: 'b17',
    name: 'Quiet',
    description: 'The power of introverts in a world that can\'t stop talking by Susan Cain.',
    price: 14.00,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1495446815901-a7297e633e8d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 3900,
    stock: 65,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'MindBooks',
  },
  {
    id: 'b18',
    name: 'The Midnight Library',
    description: 'A novel about the choices that make up a life by Matt Haig.',
    price: 15.50,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1544947950-fa07a98d237f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 7200,
    stock: 105,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'ModernFiction',
  },
  {
    id: 'b19',
    name: 'Can\'t Hurt Me',
    description: 'Master your mind and defy the odds by David Goggins.',
    price: 21.99,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1589829085413-56de8ae18c73?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 11000,
    stock: 125,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    brand: 'SelfHelpHub',
  },
  {
    id: 'b20',
    name: 'The Book Thief',
    description: 'A story about a young girl in Nazi Germany by Markus Zusak.',
    price: 12.50,
    category: 'Books',
    images: generateImages('https://images.unsplash.com/photo-1541963463532-d68292c34b19?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 5400,
    stock: 90,
    vendorId: 'v4',
    vendorName: 'BookWorm Haven',
    badges: [],
    brand: 'HistoryFiction',
  },

  // --- SPORTS & OUTDOORS (20) ---
  {
    id: 's1',
    name: 'Stainless Steel Water Bottle',
    description: 'Double-walled vacuum insulated bottle, keeps drinks cold for 24h.',
    price: 24.99,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1602143307185-84487493375e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 3400,
    stock: 100,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'HydroPure',
    material: 'Stainless Steel',
  },
  {
    id: 's2',
    name: 'Yoga Mat Pro',
    description: 'Eco-friendly, non-slip yoga mat with extra cushioning.',
    price: 45.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1592432676556-28453d07bad6?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1200,
    stock: 50,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'ZenFlow',
  },
  {
    id: 's3',
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving weights that can be adjusted from 5 to 50 lbs.',
    price: 299.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 850,
    stock: 15,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'IronFit',
  },
  {
    id: 's4',
    name: 'Resistance Bands Set',
    description: '5 levels of resistance for a full-body workout anywhere.',
    price: 25.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1598289431512-b97b0917a63e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 2100,
    stock: 120,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'FlexFit',
  },
  {
    id: 's5',
    name: 'Camping Tent 4-Person',
    description: 'Waterproof and easy to set up, perfect for family camping trips.',
    price: 149.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 430,
    stock: 10,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'WildCamp',
  },
  {
    id: 's6',
    name: 'Running Shoes Elite',
    description: 'Lightweight and responsive for high-performance running.',
    price: 120.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1500,
    stock: 60,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'SpeedRun',
  },
  {
    id: 's7',
    name: 'Hiking Backpack 50L',
    description: 'Ergonomic design with multiple compartments and rain cover.',
    price: 85.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1553062407-98eeb64c6a62?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 620,
    stock: 25,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'TrailMaster',
  },
  {
    id: 's8',
    name: 'Mountain Bike',
    description: '21-speed gears with front suspension for off-road adventures.',
    price: 450.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1485965120184-e220f721d03e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 240,
    stock: 5,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'PeakRider',
  },
  {
    id: 's9',
    name: 'Tennis Racket Pro',
    description: 'Carbon fiber frame for power and control on the court.',
    price: 159.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1617083270696-012e70149216?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 310,
    stock: 12,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'AceStrike',
  },
  {
    id: 's10',
    name: 'Basketball Official Size',
    description: 'Durable rubber cover with superior grip for indoor/outdoor play.',
    price: 29.99,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1519861531473-920036214751?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1800,
    stock: 80,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'HoopStar',
  },
  {
    id: 's11',
    name: 'Sleeping Bag 0-Degree',
    description: 'Stay warm in extreme temperatures with this mummy-style bag.',
    price: 75.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 540,
    stock: 20,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'DeepSleep',
  },
  {
    id: 's12',
    name: 'Pickleball Paddle Set',
    description: '2 lightweight paddles and 4 balls, perfect for beginners.',
    price: 59.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1617083270696-012e70149216?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 920,
    stock: 35,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'PicklePro',
  },
  {
    id: 's13',
    name: 'Foam Roller',
    description: 'High-density foam for muscle recovery and physical therapy.',
    price: 19.99,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1599447421416-3414500d18a5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 2500,
    stock: 100,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'RollRelief',
  },
  {
    id: 's14',
    name: 'Swim Goggles Anti-Fog',
    description: 'Wide vision with UV protection and leak-proof seal.',
    price: 15.50,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1551966775-a4ddc8df052b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 1100,
    stock: 150,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'AquaClear',
  },
  {
    id: 's15',
    name: 'Golf Club Set 12-Piece',
    description: 'Complete set with driver, irons, and putter for new golfers.',
    price: 399.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 180,
    stock: 8,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'FairwayPro',
  },
  {
    id: 's16',
    name: 'Soccer Ball Size 5',
    description: 'Machine-stitched for durability and consistent flight.',
    price: 24.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 1300,
    stock: 90,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'GoalMaster',
  },
  {
    id: 's17',
    name: 'Headlamp LED',
    description: 'Super bright with multiple modes, perfect for night hiking.',
    price: 18.99,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 2200,
    stock: 200,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'NightVision',
  },
  {
    id: 's18',
    name: 'Pull-Up Bar for Doorway',
    description: 'Heavy-duty steel construction, fits most standard doors.',
    price: 35.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1598289431512-b97b0917a63e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 840,
    stock: 40,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'UpperBody',
  },
  {
    id: 's19',
    name: 'Skateboard Complete',
    description: '7-layer maple deck with smooth-rolling wheels for all levels.',
    price: 55.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1547447134-cd3f5c716030?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 610,
    stock: 30,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'StreetGlide',
  },
  {
    id: 's20',
    name: 'Treadmill Folding',
    description: 'Compact design with adjustable speed and heart rate sensors.',
    price: 599.00,
    category: 'Sports & Outdoors',
    images: generateImages('https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 250,
    stock: 6,
    vendorId: 'v5',
    vendorName: 'EcoGear',
    badges: [],
    brand: 'HomeFit',
  },

  // --- BEAUTY & PERSONAL CARE (20) ---
  {
    id: 'bp1',
    name: 'Hydrating Face Serum',
    description: 'Hyaluronic acid serum for deep hydration and glowing skin.',
    price: 28.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 3200,
    stock: 80,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'SkinLuxe',
  },
  {
    id: 'bp2',
    name: 'Matte Lipstick Set',
    description: '5 long-lasting shades with a smooth, non-drying finish.',
    price: 35.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1586776977607-310e9c725c37?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1500,
    stock: 45,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'ColorPop',
  },
  {
    id: 'bp3',
    name: 'Electric Toothbrush',
    description: 'Sonic technology for a superior clean and healthier gums.',
    price: 89.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1559591937-e68fb3305558?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 2100,
    stock: 30,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'SmilePro',
  },
  {
    id: 'bp4',
    name: 'Organic Argan Oil',
    description: '100% pure cold-pressed oil for hair, skin, and nails.',
    price: 19.99,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 4500,
    stock: 120,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'NaturePure',
  },
  {
    id: 'bp5',
    name: 'Makeup Brush Set 12-Piece',
    description: 'Professional synthetic brushes for a flawless application.',
    price: 24.50,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1522338242992-e1a54906a8da?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 1800,
    stock: 60,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'Artistry',
  },
  {
    id: 'bp6',
    name: 'Charcoal Face Mask',
    description: 'Deep cleansing mask to remove impurities and minimize pores.',
    price: 15.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 2800,
    stock: 100,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'PureSkin',
  },
  {
    id: 'bp7',
    name: 'Hair Dryer Ionic',
    description: 'Fast drying with ionic technology to reduce frizz and static.',
    price: 55.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1522337360788-8b13df772ad5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 940,
    stock: 25,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'SilkBlow',
  },
  {
    id: 'bp8',
    name: 'Beard Grooming Kit',
    description: 'Includes oil, balm, comb, and brush for a well-maintained beard.',
    price: 39.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1621607512214-68297480165e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 620,
    stock: 40,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'GentleMan',
  },
  {
    id: 'bp9',
    name: 'Sunscreen SPF 50',
    description: 'Broad-spectrum protection, non-greasy and water-resistant.',
    price: 18.50,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1556228720-195a672e8a03?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 3100,
    stock: 150,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'SunSafe',
  },
  {
    id: 'bp10',
    name: 'Bath Bomb Gift Set',
    description: '6 handmade essential oil bath bombs for ultimate relaxation.',
    price: 22.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1590439471364-192aa70c0b53?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1200,
    stock: 80,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'SpaDay',
  },
  {
    id: 'bp11',
    name: 'Vitamin C Eye Cream',
    description: 'Brightens dark circles and reduces puffiness around the eyes.',
    price: 26.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 840,
    stock: 55,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'BrightEyes',
  },
  {
    id: 'bp12',
    name: 'Men\'s Cologne Signature',
    description: 'A sophisticated blend of woody and citrus notes.',
    price: 65.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 430,
    stock: 20,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'Essence',
  },
  {
    id: 'bp13',
    name: 'Nail Polish Collection',
    description: '10 vibrant, chip-resistant colors with a high-shine finish.',
    price: 29.99,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1604654894610-df490668711d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 920,
    stock: 70,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'NailArt',
  },
  {
    id: 'bp14',
    name: 'Exfoliating Body Scrub',
    description: 'Coffee and sugar scrub to smooth and revitalize skin.',
    price: 16.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1400,
    stock: 90,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    brand: 'SmoothBody',
  },
  {
    id: 'bp15',
    name: 'Hair Straightener Ceramic',
    description: 'Adjustable heat settings for sleek, straight hair in minutes.',
    price: 45.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1522337360788-8b13df772ad5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 670,
    stock: 35,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'SilkStraight',
  },
  {
    id: 'bp16',
    name: 'Retinol Night Cream',
    description: 'Anti-aging cream to reduce fine lines and improve skin texture.',
    price: 32.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1100,
    stock: 40,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'YouthRevive',
  },
  {
    id: 'bp17',
    name: 'Waterproof Mascara',
    description: 'Volumizing and lengthening mascara that stays put all day.',
    price: 14.50,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 2500,
    stock: 110,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'LashLift',
  },
  {
    id: 'bp18',
    name: 'Aloe Vera Gel',
    description: 'Soothing and cooling gel for sunburns and irritated skin.',
    price: 12.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 3500,
    stock: 200,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'NatureSooth',
  },
  {
    id: 'bp19',
    name: 'Electric Shaver for Men',
    description: 'Close and comfortable shave with flexible heads and wet/dry use.',
    price: 79.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1621607512214-68297480165e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 580,
    stock: 15,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'SmoothShave',
  },
  {
    id: 'bp20',
    name: 'Clay Pomade for Hair',
    description: 'Strong hold with a matte finish for effortless styling.',
    price: 18.00,
    category: 'Beauty & Personal Care',
    images: generateImages('https://images.unsplash.com/photo-1590439471364-192aa70c0b53?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 420,
    stock: 85,
    vendorId: 'v6',
    vendorName: 'GlowBeauty',
    badges: [],
    brand: 'StyleCraft',
  },

  // --- TOYS & GAMES (20) ---
  {
    id: 'tg1',
    name: 'Building Blocks Castle Set',
    description: '1000-piece set for building a detailed medieval castle.',
    price: 59.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1587654780291-39c9404d746b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1200,
    stock: 40,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'BlockMaster',
  },
  {
    id: 'tg2',
    name: 'Remote Control Racing Car',
    description: 'High-speed RC car with rechargeable battery and 2.4GHz remote.',
    price: 45.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1594787318286-3d835c1d207f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 850,
    stock: 25,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'SpeedRacer',
  },
  {
    id: 'tg3',
    name: 'Board Game: Strategy Quest',
    description: 'An epic strategy game for 2-4 players, perfect for family game night.',
    price: 34.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 540,
    stock: 30,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'GameNight',
  },
  {
    id: 'tg4',
    name: 'Plush Teddy Bear',
    description: 'Soft and cuddly 18-inch teddy bear, a perfect gift for all ages.',
    price: 19.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1559454403-b8fb88521f11?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 2100,
    stock: 100,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'CuddleCo',
  },
  {
    id: 'tg5',
    name: 'Educational Robot Kit',
    description: 'Build and program your own robot with this STEM-focused kit.',
    price: 89.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1535378917042-10a22c95931a?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 320,
    stock: 15,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'StemLogic',
  },
  {
    id: 'tg6',
    name: 'Wooden Train Set',
    description: 'Classic 50-piece wooden train track set with bridge and scenery.',
    price: 49.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 940,
    stock: 20,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'HeritageToys',
  },
  {
    id: 'tg7',
    name: 'Art Easel for Kids',
    description: 'Double-sided easel with chalkboard and magnetic whiteboard.',
    price: 65.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 430,
    stock: 12,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'CreativeKids',
  },
  {
    id: 'tg8',
    name: 'Digital Camera for Kids',
    description: 'Durable and easy-to-use camera with fun filters and games.',
    price: 39.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1526170315873-3a9161729b48?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 1100,
    stock: 50,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'KidPix',
  },
  {
    id: 'tg9',
    name: 'Musical Keyboard for Toddlers',
    description: 'Colorful keyboard with pre-recorded songs and animal sounds.',
    price: 24.50,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1500,
    stock: 60,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'BabyBeats',
  },
  {
    id: 'tg10',
    name: 'Outdoor Swing Set',
    description: 'Heavy-duty metal swing set with two swings and a slide.',
    price: 249.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1588072432836-e10032774350?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 180,
    stock: 5,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'PlayGround',
  },
  {
    id: 'tg11',
    name: 'Puzzle: 1000 Pieces Landscape',
    description: 'Beautiful landscape puzzle with high-quality interlocking pieces.',
    price: 15.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1585338107529-13afc5f02586?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1300,
    stock: 80,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'PuzzleMaster',
  },
  {
    id: 'tg12',
    name: 'Dollhouse with Furniture',
    description: '3-story wooden dollhouse with 15 pieces of miniature furniture.',
    price: 120.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.9,
    reviewCount: 310,
    stock: 8,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'MiniWorld',
  },
  {
    id: 'tg13',
    name: 'Science Experiment Kit',
    description: 'Perform 20+ exciting experiments with this chemistry set.',
    price: 35.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1532634922-8fe0b757fb13?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 620,
    stock: 40,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'StemLogic',
  },
  {
    id: 'tg14',
    name: 'Inflatable Kiddie Pool',
    description: 'Spacious pool for summer fun, easy to inflate and deflate.',
    price: 29.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1551966775-a4ddc8df052b?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 920,
    stock: 55,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'AquaFun',
  },
  {
    id: 'tg15',
    name: 'Walkie Talkies for Kids',
    description: 'Long-range walkie talkies with 22 channels and built-in flashlight.',
    price: 32.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1526170315873-3a9161729b48?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 670,
    stock: 35,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'ExplorerGear',
  },
  {
    id: 'tg16',
    name: 'Magic Set for Beginners',
    description: 'Learn 50+ magic tricks with this comprehensive starter kit.',
    price: 25.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1517263904808-5dc91e3e7044?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 410,
    stock: 45,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'MagicMaster',
  },
  {
    id: 'tg17',
    name: 'Scooter for Kids',
    description: '3-wheel kick scooter with adjustable height and LED wheels.',
    price: 45.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1547447134-cd3f5c716030?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 840,
    stock: 22,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'StreetGlide',
  },
  {
    id: 'tg18',
    name: 'Dinosaur Figure Set',
    description: '12 realistic dinosaur figures with a play mat and storage box.',
    price: 29.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1560160921-12911d7c6c96?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 1100,
    stock: 65,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'PrehistoricPlay',
  },
  {
    id: 'tg19',
    name: 'Karaoke Machine for Kids',
    description: 'Portable speaker with microphone and Bluetooth connectivity.',
    price: 55.00,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1516280440614-37939bbacd81?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 350,
    stock: 18,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'StarVoice',
  },
  {
    id: 'tg20',
    name: 'Baking Set for Kids',
    description: 'Real baking tools sized for small hands, includes apron and hat.',
    price: 24.99,
    category: 'Toys & Games',
    images: generateImages('https://images.unsplash.com/photo-1556910103-1c02745aae4d?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 520,
    stock: 40,
    vendorId: 'v7',
    vendorName: 'ToyWorld',
    badges: [],
    brand: 'LittleChef',
  },

  // --- AUTOMOTIVE (20) ---
  {
    id: 'a1',
    name: 'Car Dash Cam 1080p',
    description: 'Full HD dashboard camera with night vision and G-sensor.',
    price: 59.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1549490349-8643362247b5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 1500,
    stock: 30,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'RoadGuard',
  },
  {
    id: 'a2',
    name: 'Portable Car Vacuum',
    description: 'High-power corded vacuum for quick and easy car interior cleaning.',
    price: 35.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1599256621730-535171e28e50?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 2200,
    stock: 50,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'CleanDrive',
  },
  {
    id: 'a3',
    name: 'OBD2 Scanner Diagnostic Tool',
    description: 'Easily diagnose engine problems and clear check engine lights.',
    price: 45.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1530046339160-ce3e5b0c7a2f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 940,
    stock: 20,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'ScanMaster',
  },
  {
    id: 'a4',
    name: 'Car Phone Mount',
    description: 'Universal air vent mount with one-touch release mechanism.',
    price: 15.99,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1586105251261-72a756657761?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 3500,
    stock: 150,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'HoldTight',
  },
  {
    id: 'a5',
    name: 'Jump Starter Power Bank',
    description: 'Powerful jump starter for cars with built-in USB ports for charging.',
    price: 89.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1621905238291-08823ef2c0ae?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 610,
    stock: 15,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'PowerStart',
  },
  {
    id: 'a6',
    name: 'Leather Seat Covers Set',
    description: 'Premium faux leather covers for front and rear seats.',
    price: 129.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 430,
    stock: 10,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'LuxeInterior',
  },
  {
    id: 'a7',
    name: 'Car Air Purifier',
    description: 'Ionic purifier to remove odors, smoke, and allergens.',
    price: 24.50,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.3,
    reviewCount: 1100,
    stock: 60,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'FreshAir',
  },
  {
    id: 'a8',
    name: 'Microfiber Cleaning Cloths',
    description: '12-pack of ultra-soft cloths for scratch-free car detailing.',
    price: 12.99,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1607860108855-64acf2078ed9?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 2800,
    stock: 200,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'ShineMaster',
  },
  {
    id: 'a9',
    name: 'Tire Pressure Gauge',
    description: 'Digital gauge with backlit LCD for easy reading in any light.',
    price: 14.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1597328290883-50c5787b7c7e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1200,
    stock: 100,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'PressureWise',
  },
  {
    id: 'a10',
    name: 'Car Wax and Polish Kit',
    description: 'Includes premium carnauba wax, applicator pads, and towels.',
    price: 39.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1607860108855-64acf2078ed9?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 540,
    stock: 40,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'GlossPro',
  },
  {
    id: 'a11',
    name: 'Bluetooth FM Transmitter',
    description: 'Stream music and take hands-free calls in older cars.',
    price: 19.99,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1615526675159-e248c3021d3f?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.4,
    reviewCount: 3200,
    stock: 80,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'AudioLink',
  },
  {
    id: 'a12',
    name: 'Car Trunk Organizer',
    description: 'Collapsible storage with multiple compartments and non-slip bottom.',
    price: 29.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 1800,
    stock: 55,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'TidyTrunk',
  },
  {
    id: 'a13',
    name: 'Emergency Roadside Kit',
    description: 'Includes jumper cables, tow strap, flashlight, and first aid kit.',
    price: 49.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1584467735815-f778f274e296?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 320,
    stock: 25,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'SafeDrive',
  },
  {
    id: 'a14',
    name: 'Car Sun Shade',
    description: 'Reflective shade to keep your car interior cool and protect the dash.',
    price: 12.50,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 5200,
    stock: 120,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'CoolRide',
  },
  {
    id: 'a15',
    name: 'LED Interior Lights',
    description: 'App-controlled RGB lights to customize your car\'s ambiance.',
    price: 22.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1549490349-8643362247b5?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 920,
    stock: 45,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'GlowDrive',
  },
  {
    id: 'a16',
    name: 'Steering Wheel Cover',
    description: 'Soft, breathable microfiber leather for a better grip and comfort.',
    price: 18.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 1400,
    stock: 70,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'GripMaster',
  },
  {
    id: 'a17',
    name: 'Car Windshield Wiper Blades',
    description: 'High-performance blades for clear visibility in all weather.',
    price: 24.99,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1597328290883-50c5787b7c7e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.7,
    reviewCount: 670,
    stock: 35,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'ClearView',
  },
  {
    id: 'a18',
    name: 'Blind Spot Mirrors',
    description: 'Set of 2 convex mirrors to expand your field of vision.',
    price: 9.99,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.6,
    reviewCount: 2500,
    stock: 110,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'WideAngle',
  },
  {
    id: 'a19',
    name: 'Car Battery Charger',
    description: 'Smart charger and maintainer for all 12V lead-acid batteries.',
    price: 45.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1621905238291-08823ef2c0ae?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.8,
    reviewCount: 420,
    stock: 15,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'ChargePro',
  },
  {
    id: 'a20',
    name: 'Headlight Restoration Kit',
    description: 'Easily clear cloudy, yellowed headlights for improved safety.',
    price: 19.00,
    category: 'Automotive',
    images: generateImages('https://images.unsplash.com/photo-1597328290883-50c5787b7c7e?q=80&w=600&h=600&auto=format&fit=crop'),
    rating: 4.5,
    reviewCount: 850,
    stock: 30,
    vendorId: 'v8',
    vendorName: 'AutoPro Parts',
    badges: [],
    brand: 'BrightBeam',
  },
];

export const MOCK_VENDORS = [
  {
    id: 'v1',
    name: 'TechHub Solutions',
    logo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?q=80&w=100&h=100&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&h=400&auto=format&fit=crop',
    description: 'Your one-stop shop for the latest in consumer electronics and gadgets.',
    rating: 4.8,
    isTopSeller: true,
    isFastShipper: true,
    isHighlyRated: true,
  },
  {
    id: 'v2',
    name: 'Comfort Living',
    logo: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=100&h=100&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?q=80&w=1200&h=400&auto=format&fit=crop',
    description: 'High-quality furniture and home decor for a modern lifestyle.',
    rating: 4.5,
    isTopSeller: false,
    isFastShipper: true,
    isHighlyRated: true,
  },

  ///HOLI SALE IMAGES//
{
  id: "h1",
  name: "Holi Color Pack",
  price: 499,
  discount: 20,
  category: "Holi",
  stock: 50,
  rating: 4.5,
  images: [
    "https://images.unsplash.com/photo-1615916571200-3a0dbd0d66c2",
    "https://images.unsplash.com/photo-1589998059171-988d887df646"
  ]
},
{
  id: "h2",
  name: "Water Pichkari Gun",
  price: 299,
  discount: 15,
  category: "Holi",
  stock: 40,
  rating: 4.2,
  images: [
    "https://images.unsplash.com/photo-1589998059171-988d887df646"
  ]
},
{
  id: "h3",
  name: "White Holi T-Shirt",
  price: 699,
  discount: 25,
  category: "Holi",
  stock: 30,
  rating: 4.6,
  images: [
    "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab"
  ]
}
];
